Repository ProjectPythia/pythia-foundations, pull requests merged in 2021-06, with the labels that each got.

#55 Quickstart for Python notebook
  _toc.yml
  foundations/Hello.ipynb
  foundations/basic-python.md
  foundations/getting-started-python.md
  foundations/quickstart.ipynb
Labels: content, ready for review

#65 Update overview pages for foundations section
  foundations/getting-started-python.md
  foundations/overview.md
Labels: content, ready for review

#66 Link overview pages and suggest order
  core/numpy.md
  core/overview.md
  foundations/overview.md
Labels: content, ready for review

#58 Add pandas example based on XDev workshop
  _toc.yml
  core/pandas.md
  core/pandas/enso_data.csv
  core/pandas/pandas_fullNotebook.ipynb
Labels: content, ready for review

#53 Create notebook template for contributors
  _config.yml
  _toc.yml
  preamble/how-to-contribute.md
  preamble/template.ipynb
Labels: content, ready for review

#61 Add GH workflow for checking external links
  .github/workflows/link-checker.yaml
Labels: infrastructure, ready to merge

#57 Fit 01_Cartopy_Intro notebook to proposed Foundations template
  core/cartopy.md
  core/cartopy/01_Cartopy_Intro.ipynb
Labels: content, hackathon

#70 Add jupyterlab to pythia-book-dev environment
  environment.yml
Labels: infrastructure

#38 Drop in Unidata datetime intro materials notebook
  _toc.yml
  core/datetime.md
  core/datetime/datetime.ipynb
  core/pandas/enso_data.csv
  core/pandas/pandas_fullNotebook.ipynb
  environment.yml
Labels: content, hackathon, ready for review

#37 Drop in Unidata matplotlib workshop notebook
  _toc.yml
  core/matplotlib.md
  core/matplotlib/matplotlib.ipynb
Labels: content, ready for review

#36 Drop in Unidata netcdf+CF notebook for core/data-formats
  _toc.yml
  core/data-formats/netcdf-cf.ipynb
  core/pandas/nino_analyzed_output.csv
  environment.yml
  preamble/template.ipynb
Labels: content, hackathon, ready for review

#39 Drop in Unidata numpy workshop notebooks
  _toc.yml
  core/numpy/array_index.png
  core/numpy/intermediate-numpy.ipynb
  core/numpy/numpy-basics.ipynb
  core/numpy/numpy-broadcasting.ipynb
  core/pandas/nino_analyzed_output.csv
  foundations/quickstart.ipynb
  preamble/template.ipynb
Labels: content, hackathon, ready for review

#79 Update landing page for NumPy chapter
  core/numpy.md
Labels: ready for review

#33 Drop in Unidata xarray workshop notebook
  _toc.yml
  core/xarray.md
  core/xarray/nc-cf.ipynb
  core/xarray/xarray-intro.ipynb
  environment.yml
Labels: content, ready for review

#80 Temporary cover art
  images/pretty-earth.png
  landing-page.ipynb
  landing-page.md
Labels: ready for review

#84 Improve page footer: links to Pythia portal and Contributors guide
  _config.yml
Labels: infrastructure, ready for review
